---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "* $TITLE ([#$NUMBER]($URL)) @$AUTHOR"
template: |
  # What’s changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: "🚨 Breaking changes"
    when:
      labels:
        - "breaking-change"
  - title: "✨ New themes"
    when:
      labels:
        - "new-theme"
  - title: "🐛 Bug fixes"
    when:
      labels:
        - "bugfix"
  - title: "🎨 Theme updates"
    when:
      labels:
        - "theme-updates"
  - title: "🚀 Enhancements"
    when:
      labels:
        - "enhancement"
  - title: "🧰 Maintenance"
    when:
      labels:
        - "maintenance"
  - title: "📖 Documentation"
    when:
      labels:
        - "documentation"
  - title: "⬆️ Dependency updates"
    when:
      labels:
        - "dependencies"
    collapse-after: 0
  - type: "pre-exclude"
    when:
      labels:
        - "skip-changelog"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - "major"
        - "breaking-change"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - "minor"
        - "new-theme"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - "patch"
