---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "* $TITLE ([#$NUMBER]($URL)) @$AUTHOR"
template: |
  # What’s changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New themes"
    labels:
      - "new-theme"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🎨 Theme updates"
    labels:
      - "theme-updates"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "📖 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    labels:
      - "dependencies"
    collapse-after: 1

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-theme"
  patch:
    labels:
      - "patch"
  default: patch

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "skip-changelog"
    branch:
      - "/release\/.+/"
  - label: "new-theme"
    title:
      - "/^Add .+ theme$/"
    branch:
      - "/new-theme\/.+/"
