title: "Theme request"
labels: ["theme-request"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for theme requests only!

        If you found a bug, please use the [Bug Report][bug-report] form.

        For general questions, please use the [Discussions][discussions] section.

        [bug-report]: https://github.com/node-red-contrib-themes/theme-collection/issues/new?template=01-bug-report.yml
        [discussions]: https://github.com/node-red-contrib-themes/theme-collection/discussions/new?category=general

  - type: textarea
    attributes:
      label: Details
      description: |
        Details related to the theme you are requesting:

        - short description
        - links for reference
        - screenshots
    validations:
      required: true
