---
name: "Check Pull Request labels"

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  check_labels:
    name: "Check Pull Request labels"
    runs-on: ubuntu-slim
    steps:
      - uses: ludeeus/action-require-labels@2.0.0
        with:
          labels: >-
            breaking-change, bugfix, documentation, enhancement, new-theme,
            dependencies, maintenance, theme-updates, skip-changelog, no-stale
