---
name: "Prettier"

on:
  pull_request:

permissions: {}

jobs:
  prettier:
    name: "Prettier"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6.0.3

      - name: "Prettier check"
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: "--check ."
