---
name: "Prettier"

on:
  pull_request:

jobs:
  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.2.1

      - name: "Prettier check"
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--check ."
