---
name: "Release Drafter"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions: {}

jobs:
  update_release_draft:
    name: "Update Release Draft"
    permissions:
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
