---
name: "Release Publish"

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions: {}

jobs:
  npm-publish:
    name: "Publish"
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Node"
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "lts/*"

      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Install dependencies"
        run: npm install

      - name: "Checkout Node-RED"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          repository: node-red/node-red
          path: node-red

      - name: "Build"
        run: npm run build

      - name: "Publish to npm"
        run: npm publish
