---
name: "Release Publish"

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions: {}

jobs:
  npm-publish:
    name: "Publish"
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Node"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Install dependencies"
        run: npm install

      - name: "Checkout Node-RED"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: node-red/node-red
          path: node-red

      - name: "Build"
        run: npm run build

      - name: "Publish to npm"
        run: npm publish
