---
name: "Release Drafter"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_release_draft:
    name: "Update Release Draft"
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
